services:
    gywaschoolbundle.subjectManager:
        class: GyWa\SchoolBundle\SubjectManager
        arguments:
          - "@database_connection"
          - "@monolog.logger"
        public: true

    gywaschoolbundle.categoryManager:
        class: GyWa\SchoolBundle\CategoryManager
        arguments:
          - "@database_connection"
          - "@monolog.logger"
        public: true

    gywaschoolbundle.contentelement.subjectlist:
        class: GyWa\SchoolBundle\Controller\ContentElement\SubjectListController
        arguments:
          - "@database_connection"
        tags:
          - { name: contao.content_element, category: gywa_school }
        public: true

    gywaschoolbundle.contentelement.teacherlist:
        class: GyWa\SchoolBundle\Controller\ContentElement\TeacherListController
        arguments:
          - "@database_connection"
        tags:
          - { name: contao.content_element, category: gywa_school }
        public: true